### ISSUE TITLE
Extra options for each item: datasheet, LCSC link, JLCPCB link?

### ISSUE THREAD

**Issue by m1geo** [Joeskaife/JLCQT#7]
Have a link to the datasheet (in the CSV) and the LCSC/JLCPCB link through the stock code number?

**Comment by Joeskaife** [comment]
OK, I've done it for datasheet links only.

**Comment by m1geo** [comment]
The CSV contains a LCSC stock code for each entry, which you can pass to LCSC or JLCPCB to go directly to their page for the item?

**Comment by Joeskaife** [comment]
On LCSC the item page is built from Javascript and named on a more-or-less random basis.

Similarly on JLC, but the JLC part search page is based on HTML parameter passing so I can pass a link based on a search entry for the JLC database. Eg: 
`href=https://jlcpcb.com/parts/componentSearch?isSearch=true&searchTxt=C1710`
If C1710 is a unique enough string in the database, then you'll get just that part, otherwise you'll get a list of parts with "C1710" in them somewhere.

I don't know of any other way to link to either JLC or LCSC but if someone spots a way.....

**Comment by m1geo** [comment]
Using the code at "https://lcsc.com/search?q=Cxxxx" get's recognised as a unique stock code. Doesn't work for JLCPCB as you say.

**Comment by Joeskaife** [comment]
Ok, that LCSC link works really well. Now we've got both datasheet link (if in the CSV file) and part link.
